#!/bin/bash
# start.sh - Start OpenClaw gateway + deployer and print completion summary

echo "--- Starting OpenClaw gateway + deployer ---"
echo ""

cd "$SCRIPT_DIR"
docker compose up -d openclaw-gateway deployer 2>&1

# shellcheck source=/dev/null
source "$SCRIPT_DIR/deployer-workspace/config/.env"
DOCKER_NETWORK="${DOCKER_NETWORK:-openclaw_network}"
OPENCLAW_CONFIG_FILE="$OPENCLAW_CONFIG_DIR/openclaw.json"

echo ""
echo "============================================"
echo "  Setup Complete!"
echo "============================================"
echo ""
echo "  OpenClaw is running in Docker."
echo "  Deployer sidecar is running alongside it."
echo ""
echo "  Architecture:"
echo "    - OpenClaw (no Docker access) writes code to apps/"
echo "    - Deployer sidecar (Docker access) handles deployments"
echo "    - OpenClaw calls deployer via HTTP on the internal network"
echo ""
echo "  Config:"
echo "    - Opus (claude-opus-4-6) as primary model"
echo "    - Haiku (claude-haiku-3-5) for sub-agents"
echo "    - Workspace mounted from: $SCRIPT_DIR"
echo "    - Docker network: $DOCKER_NETWORK"
echo ""
echo "  Remaining manual step:"
echo ""
echo "  1. Edit WhatsApp number in config:"
echo "     nano $OPENCLAW_CONFIG_FILE"
echo "     Replace '+YOUR_NUMBER_HERE' with your number"
echo ""
echo "  2. Add the Docker network to Traefik:"
echo "     Edit your Traefik docker-compose.yml"
echo "     Add '$DOCKER_NETWORK' as an external network"
echo "     Restart Traefik"
echo ""
echo "  3. Test it! Send a WhatsApp message:"
echo "     'Hello! What can you help me build?'"
echo ""
echo "  Commands:"
echo "    docker compose logs -f openclaw-gateway   # View OpenClaw logs"
echo "    docker compose logs -f deployer           # View deployer logs"
echo "    docker compose restart openclaw-gateway    # Restart OpenClaw"
echo "    docker compose down                        # Stop everything"
echo "    docker compose run --rm openclaw-cli channels login  # Re-scan QR"
echo ""
echo "============================================"
